import 'package:audioplayers/audioplayers.dart';

import 'tune/tune.dart';

/// Plays a tune, and says where it has got to.
///
/// Thin on purpose. Everything that decides anything — when a note is due,
/// whether a tap was in time, what it scored — is somewhere else and knows
/// nothing about audio, so all of it can be tested without a speaker. What is
/// left here is starting a file and reading its position, which is the only
/// part that genuinely needs a device.
class Music {
  Music({AudioPlayer? player}) : _player = player ?? AudioPlayer();

  final AudioPlayer _player;

  /// Where each tune's sound lives. Generated by tool/build_audio.dart from
  /// the same notes the falling notes come from.
  static String fileOf(Tune tune) =>
      '${tune.name.toLowerCase().replaceAll(' ', '-')}.wav';

  Stream<Duration> get positions => _player.onPositionChanged;
  Stream<void> get finished => _player.onPlayerComplete;

  Future<void> play(Tune tune) async {
    await _player.stop();
    await _player.setReleaseMode(ReleaseMode.stop);
    await _player.play(AssetSource(fileOf(tune)));
  }

  Future<void> stop() => _player.stop();

  Future<void> pause() => _player.pause();

  Future<void> carryOn() => _player.resume();

  Future<void> throwAway() => _player.dispose();
}
