// This is a command line tool whose whole job is to print and write a file.
// ignore_for_file: avoid_print

import 'dart:io';

import 'package:vaultline/sim/maker.dart';
import 'package:vaultline/sim/passable.dart';
import 'package:vaultline/sim/runner.dart';

/// Makes the stretches the game is built from, and writes them down.
///
/// Run with: dart run tool/build_stretches.dart [how many of each]
///
/// The game promises that every stretch it puts in front of a player can be
/// got through. That promise is only worth making if something checks it, and
/// checking it means playing the stretch — pressing the button at every step,
/// both ways, until either the end is reached or there is nowhere left to try.
/// It takes a few hundred milliseconds for a short stretch and a few seconds
/// for a long one, which is not a thing to do on a phone while somebody waits.
/// So it is done here, once, and the answers are committed.
///
/// What is written out is the tiles, the steps the button was held on in the
/// line that proved it, and how many separate presses that was. The line is
/// kept because a proof nobody can replay is a claim: the tests replay every
/// one of them.
void main(List<String> args) {
  final each = args.isEmpty ? 30 : int.parse(args.first);
  const shapes = [1, 2, 3, 4];

  final made = <({int obstacles, Stretch stretch})>[];
  final watch = Stopwatch()..start();

  for (final obstacles in shapes) {
    var kept = 0;
    var seed = 0;
    while (kept < each && seed < each * 6) {
      final stretch = const Maker(
        verifier: Verifier(mostStates: 900000),
      ).make(seed: seed, obstacles: obstacles);
      seed++;
      if (stretch == null) continue;

      // The proof, checked here as well as in the tests, because a tool that
      // writes down a line it has not played is a tool nobody should trust.
      final replay = playWith(stretch.ground, stretch.holds);
      if (replay.ending != Ending.through) {
        print('  seed $seed: the line does not play out — dropped');
        continue;
      }

      made.add((obstacles: obstacles, stretch: stretch));
      kept++;
    }
    print('$obstacles obstacles: kept $kept of $seed tried, '
        '${(watch.elapsedMilliseconds / 1000).toStringAsFixed(0)}s so far');
  }
  watch.stop();

  made.sort((a, b) => a.stretch.jumps.compareTo(b.stretch.jumps));

  final buffer = StringBuffer()
    ..writeln('// Generated by tool/build_stretches.dart. Do not edit by hand.')
    ..writeln('//')
    ..writeln('// The stretches the game is built from. Every one was played')
    ..writeln('// to the end by the verifier in lib/sim/passable.dart before')
    ..writeln('// it went in this list, and the steps it held the button on')
    ..writeln('// are kept beside it so the proof can be replayed.')
    ..writeln('//')
    ..writeln('// ${made.length} stretches, sorted by how many presses they')
    ..writeln('// need.')
    ..writeln()
    ..writeln('const List<(String, int, List<int>)> kStretches = [');
  for (final one in made) {
    buffer.writeln("  ('${one.stretch.written}', ${one.stretch.jumps}, "
        '${one.stretch.holds}),');
  }
  buffer.writeln('];');

  File('lib/sim/stretches.dart').writeAsStringSync(buffer.toString());

  print('');
  print('wrote ${made.length} stretches in '
      '${(watch.elapsedMilliseconds / 1000).toStringAsFixed(0)}s');
}
