import 'dart:io';

/// Turns a system word list into the one the game ships.
///
/// Run with: dart run tool/build_words.dart /usr/share/dict/words
///
/// The list a word game ships is part of its design, not an asset. A player
/// who traces something real and is told it is not a word stops trusting the
/// game, and one who is credited for a plural of an abbreviation notices that
/// too. So the rules for what gets in are written here rather than left to
/// whatever the machine happened to have installed.
void main(List<String> args) {
  final source = File(args.isEmpty ? '/usr/share/dict/words' : args.first);
  if (!source.existsSync()) {
    stderr.writeln('no word list at ${source.path}');
    exit(2);
  }

  final kept = <String>{};
  for (final line in source.readAsLinesSync()) {
    final word = line.trim();

    // Lower case only, which drops proper nouns, and letters only, which
    // drops the possessives and abbreviations the list is full of.
    if (!RegExp(r'^[a-z]+$').hasMatch(word)) continue;

    // Three letters is too easy to hit by accident on a crowded board, and
    // nine is longer than a trace anybody wants to keep their thumb down for.
    if (word.length < 4 || word.length > 9) continue;

    kept.add(word);
  }

  final words = kept.toList()..sort();
  final buffer = StringBuffer()
    ..writeln('// Generated by tool/build_words.dart. Do not edit by hand.')
    ..writeln('//')
    ..writeln('// ${words.length} words, four to nine letters, lower case only.')
    ..writeln()
    ..writeln('const List<String> kWords = <String>[');
  for (final word in words) {
    buffer.writeln("  '$word',");
  }
  buffer.writeln('];');

  File('lib/game/words.dart').writeAsStringSync(buffer.toString());
  stdout.writeln('wrote ${words.length} words');
}
