// This is a command line tool whose whole job is to print and to write a file.
// ignore_for_file: avoid_print

import 'dart:io';

import 'package:fanwright/game/solver.dart';
import 'package:fanwright/game/table.dart';

/// Works out which deals are worth handing to a player, and writes them down.
///
/// Run with: dart run tool/build_book.dart [how many to try]
///
/// The game promises that every deal it deals can be won. That promise is only
/// worth making if something checks it, and checking it is a search — which
/// takes a few milliseconds for most deals and half a minute for the odd one.
/// Doing that on a phone while somebody waits is not on, so it is done here,
/// once, and the answer is committed.
///
/// A deal is kept if the solver wins it inside [budget] positions. Deals it
/// cannot are dropped rather than shipped: some of them are winnable by a
/// longer search and one or two are not winnable at all, and from where the
/// player sits there is no difference between a deal nobody can win and a deal
/// the hint button cannot help with.
void main(List<String> args) {
  const budget = 100000;
  final tries = args.isEmpty ? 500 : int.parse(args.first);

  final kept = <int>[];
  final dropped = <int>[];
  var positions = 0;
  final watch = Stopwatch()..start();

  for (var number = 1; number <= tries; number++) {
    final found = Solver(mostPositions: budget).solve(Table.deal(number));
    positions += found.looked;
    if (found.won) {
      kept.add(number);
    } else {
      dropped.add(number);
      print('  dropped $number '
          '(${found.gaveUp ? 'gave up' : 'no win exists'})');
    }
  }
  watch.stop();

  final buffer = StringBuffer()
    ..writeln('// Generated by tool/build_book.dart. Do not edit by hand.')
    ..writeln('//')
    ..writeln('// The deals this game hands out. Every one was proved winnable')
    ..writeln('// by the solver in lib/game/solver.dart, inside $budget')
    ..writeln('// positions, before it went in this list.')
    ..writeln('//')
    ..writeln('// ${kept.length} of the first $tries deals. The ones missing')
    ..writeln('// are the deals the solver could not win in that budget:')
    ..writeln('// ${dropped.join(', ')}')
    ..writeln()
    ..writeln('const List<int> kDeals = <int>[');
  for (var i = 0; i < kept.length; i += 12) {
    final row = kept.skip(i).take(12).join(', ');
    buffer.writeln('  $row,');
  }
  buffer.writeln('];');

  File('lib/game/deals.dart').writeAsStringSync(buffer.toString());

  print('');
  print('kept ${kept.length} of $tries, dropped ${dropped.length}');
  print('${(positions / tries).round()} positions a deal on average, '
      '${(watch.elapsedMilliseconds / 1000).toStringAsFixed(1)}s in all');
}
