import 'dart:io';

/// Turns Latchword's word list into the two this game ships.
///
/// Run with: dart run tool/build_words.dart ../Latchword/lib/game/words.dart
///
/// A ladder game lives or dies on its list. Every rung has to be a word the
/// player would call a word, and — just as important — every word in the list
/// has to be one they might think of, because a ladder whose shortest way
/// through goes by a word nobody knows is a ladder that reads as impossible.
///
/// So this takes the list Latchword already ships, which was cut from the
/// system dictionary to letters-only and lower case, and keeps the four and
/// five letter words out of it. Sharing it rather than cutting a new one from
/// the system list matters: two word games in one collection disagreeing
/// about whether something is a word is worse than either of them being
/// wrong.
void main(List<String> args) {
  final source = File(args.isEmpty
      ? '../Latchword/lib/game/words.dart'
      : args.first);
  if (!source.existsSync()) {
    stderr.writeln('no word list at ${source.path}');
    exit(2);
  }

  final words = RegExp("'([a-z]+)'")
      .allMatches(source.readAsStringSync())
      .map((found) => found.group(1)!)
      .toSet();

  final four = (words.where((word) => word.length == 4).toList())..sort();
  final five = (words.where((word) => word.length == 5).toList())..sort();

  _write('lib/ladder/words.dart', four, five);
  stdout.writeln('${four.length} of four letters, ${five.length} of five');
}

void _write(String path, List<String> four, List<String> five) {
  final out = StringBuffer()
    ..writeln('// Generated by tool/build_words.dart. Do not edit by hand.')
    ..writeln('//')
    ..writeln('// ${four.length} words of four letters and ${five.length} of')
    ..writeln('// five, out of the list Latchword ships.')
    ..writeln()
    ..writeln('const List<String> kFour = <String>[');
  for (final word in four) {
    out.writeln("  '$word',");
  }
  out
    ..writeln('];')
    ..writeln()
    ..writeln('const List<String> kFive = <String>[');
  for (final word in five) {
    out.writeln("  '$word',");
  }
  out.writeln('];');
  File(path).writeAsStringSync(out.toString());
}
